/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dwsuperstorequeueingsystem;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author User
 */
public class DWSUserPOV extends javax.swing.JFrame {
    private DWSGetTokenNumFrame getTokenNum;
    /**
     * Creates new form DWSUserPOV
     */
    public DWSUserPOV() {
        initComponents();
        w1CurrentServing.setFont(new Font("Monospaced", Font.BOLD, 22));
        w1CurrentServing.setForeground(Color.YELLOW);
        w2CurrentServing.setFont(new Font("Monospaced", Font.BOLD, 22));
        w2CurrentServing.setForeground(Color.YELLOW);
        pw3CurrentServing.setFont(new Font("Monospaced", Font.BOLD, 22));
        pw3CurrentServing.setForeground(Color.YELLOW);
        w1NextServing.setFont(new Font("Monospaced", Font.BOLD, 22));
        w1NextServing.setForeground(Color.YELLOW);
        w2NextServing.setFont(new Font("Monospaced", Font.BOLD, 22));
        w2NextServing.setForeground(Color.YELLOW);
        pw3NextServing.setFont(new Font("Monospaced", Font.BOLD, 22));
        pw3NextServing.setForeground(Color.YELLOW);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        w1CurrentServing = new javax.swing.JLabel();
        w2CurrentServing = new javax.swing.JLabel();
        pw3CurrentServing = new javax.swing.JLabel();
        w1NextServing = new javax.swing.JLabel();
        w2NextServing = new javax.swing.JLabel();
        pw3NextServing = new javax.swing.JLabel();
        UserPOVBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(w1CurrentServing, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 100, 30));
        getContentPane().add(w2CurrentServing, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 100, 30));
        getContentPane().add(pw3CurrentServing, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 100, 30));
        getContentPane().add(w1NextServing, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 110, 30));
        getContentPane().add(w2NextServing, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 110, 30));
        getContentPane().add(pw3NextServing, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 110, 30));

        UserPOVBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DWSuperstoreQueueing System/SERVING NOW  ALL WINDOW (USER POV) .png"))); // NOI18N
        getContentPane().add(UserPOVBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DWSUserPOV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DWSUserPOV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DWSUserPOV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DWSUserPOV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DWSUserPOV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UserPOVBG;
    public javax.swing.JLabel pw3CurrentServing;
    public javax.swing.JLabel pw3NextServing;
    public javax.swing.JLabel w1CurrentServing;
    public javax.swing.JLabel w1NextServing;
    public javax.swing.JLabel w2CurrentServing;
    public javax.swing.JLabel w2NextServing;
    // End of variables declaration//GEN-END:variables
}
